services:
  - type: web
    name: jalaquduq-bot-new
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER_EXTERNAL_URL
        sync: false
